name: Terraform AWS Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: 'us-east-1'
      TF_VAR_region: 'us-east-1'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Change to AWS Cloud Directory
        run: |
          cd clouds/aws

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'us-east-1'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Create Bucket S3
        run: |
            BUCKET_NAME="pos-fiap-schepis-$(date +'%Y%m%d-%H%M%S')"
            EXISTING_BUCKET=$(aws s3api list-buckets --query "Buckets[?contains(Name, 'pos-fiap-schepis')].Name" --output text)
              
            if [[ -n "$EXISTING_BUCKET" ]]; then
              echo "✅ Found existing S3 bucket: $EXISTING_BUCKET"
              BUCKET_NAME="$EXISTING_BUCKET"  # Set BUCKET_NAME to existing bucket
            else
              BUCKET_NAME="pos-fiap-schepis-$(date +'%Y%m%d-%H%M%S')"  # Create unique bucket name
              echo "🚀 Creating new S3 bucket: $BUCKET_NAME..."
              aws s3api create-bucket --bucket "$BUCKET_NAME" --region us-east-1
              aws s3api put-bucket-versioning --bucket "$BUCKET_NAME" --versioning-configuration Status=Enabled
              echo "✅ S3 bucket '$BUCKET_NAME' has been created and versioning enabled."
            fi
            
            # Output the final bucket name
            echo "🌍 Using S3 bucket: $BUCKET_NAME"

      - name: Terraform Init
        run: |
          cd clouds/aws
          terraform init \
            -backend-config="bucket=$BUCKET_NAME" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true"

      - name: Terraform Plan
        run: |
          cd clouds/aws
          terraform plan -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -out=plan.tfplan

      - name: Terraform Apply
        run: |
          cd clouds/aws 
          terraform apply -auto-approve plan.tfplan